name: cli
description: A sample command-line application.
version: 0.0.0

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  args: 1.6.0
  colorize: 2.0.0
  json2yaml: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
